FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src


COPY ["ToDoListWebApp/ToDoListWebApp.csproj", "ToDoListWebApp/"]
RUN dotnet restore "ToDoListWebApp/ToDoListWebApp.csproj"


COPY . .
WORKDIR "/src/ToDoListWebApp"
RUN dotnet build "ToDoListWebApp.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ToDoListWebApp.csproj" -c Release -o /app/publish


FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80

COPY --from=publish /app/publish .


ENTRYPOINT ["dotnet", "ToDoListWebApp.dll"]
