
FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80


FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["ToDoListWebApp/ToDoListWebApp.csproj", "ToDoListWebApp/"]
RUN dotnet restore "ToDoListWebApp/ToDoListWebApp.csproj"
COPY . .
WORKDIR "/src/ToDoListWebApp"
RUN dotnet build "ToDoListWebApp.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ToDoListWebApp.csproj" -c Release -o /app/publish


FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ToDoListWebApp.dll"]
